### PR TITLE
Add Arch Linux installation instructions

### PR DESCRIPTION
**Pull request by ejuarezg**
I started using your code and decided to create an AUR package. I provided installation instructions in the README. Feel free to modify them.

On a separate note, can you upload a license for your code. It'd be great to provide users of the AUR package with a copy of the license.

Thanks!

### CODE REVIEW

**Comment by RMTT** [comment]
Thanks for your help,i will add a license,but the code is very easy,is it really necessary?

**Comment by RMTT** [comment]
Hey,you should place the lib file to `/usr/lib/lua/<lua version>/` folder

**Comment by ejuarezg** [comment]
Thanks for the merge.

> i will add a license,but the code is very easy,is it really necessary?

I also don't think the license is really necessary for such a small codebase, but technically, I wouln't be able to distribute an AUR package without one. I think the MIT license you added is a great choice.

> Hey,you should place the lib file to /usr/lib/lua/<lua version>/ folder

I thought about doing this but since this package provides extra functionality, I figured I would be best to have it's own folder as per the package guidelines. Also, if lua changes version, I don't want any symbolic links or hardcoded paths to liblua_pam.so to be broken.

**Comment by RMTT** [comment]
> I thought about doing this but since this package provides extra functionality, I figured I would be best to have it's own folder as per the package guidelines. Also, if lua changes version, I don't want any symbolic links or hardcoded paths to liblua_pam.so to be broken.

Maybe you can create a soft link to `/usr/lib/lua/<lua version>` by default.

**Pull request merged**
